### ISSUE TITLE
Feature request : Add a copy to clipboard button next to links

### ISSUE THREAD

**Issue by manojm321** [paveyry/better-hangoutschat#17]
More often I need to copy the links and share it with someone. Right now I have to right click on "Link" and copy the address.

If possible it would be nice to have a one click copy button.

**Comment by paveyry** [comment]
Hi.
This is now implemented in version v4.2. 
https://github.com/paveyry/better-hangoutschat/releases/tag/v4.2 
<img width="402" alt="Screenshot 2021-03-22 at 17 14 36" src="https://user-images.githubusercontent.com/3884900/112032544-6b519100-8b34-11eb-9b6a-318720157152.png">

**Comment by paveyry** [comment]
Google has broken this feature in their latest GHC update and access to the clipboard is now blocked. I am reopening this issue because I hope I will be able to find a workaround for it.

**Comment by paveyry** [comment]
Readded this feature in v6.1.1
