### ISSUE TITLE
Confusing stderr text from `make gmonkey`

### ISSUE THREAD

**Issue by tsiemens** [paveyry/better-hangoutschat#18]
If I run the generate_patch.sh script or `make gmonkey`, it will emit to stderr, even when it succeeds, which is rather confusing.
If I don't pay attention to the return code of the command, it looks like a failure, when in reality it is not.

```
❯ make gmonkey
./generate_patch.sh
grep: : No such file or directory
grep: : No such file or directory
grep: : No such file or directory
❯
```

I would expect to not see this if it is expected, without having debug traces turned on.

**Comment by paveyry** [comment]
This issue should be resolved now since all these commands have disappeared now that the electron client has been removed.
