### ISSUE TITLE
Chat/Room Row Padding

### ISSUE THREAD

**Issue by rnc** [paveyry/better-hangoutschat#20]
Could there be an option to adjust the whitespace padding on the left hand pane chat/room box rows. For example the original is

![image](https://user-images.githubusercontent.com/1169793/118646469-25cddf00-b7d8-11eb-8d90-ba21eca943e4.png)

but the new is 

![image](https://user-images.githubusercontent.com/1169793/118646543-39794580-b7d8-11eb-994c-6d269b4fab43.png)

and my _personal_ preference is the original padding looks nicer on large screens. 

I am using Firefox 88.0.1 on Fedora 34

**Comment by paveyry** [comment]
Unfortunately, I can't make all this parametric. Your best option would be to fork this repo, change the values you want, and either use your custom extension unsigned in Firefox Dev release, or sign your own version with mozilla too

**Comment by rnc** [comment]
Ok no problem! Can you point me to what values define the padding is defined in the extension?
