### ISSUE TITLE
Current room highlight

### ISSUE THREAD

**Issue by rnc** [paveyry/better-hangoutschat#21]
Having tried a few of the different themes (normal, slack, dark) on Firefox 88.0.1 on Fedora 34 one thing I did notice is that the highlight for which room I am currently in often doesn't show (or disappears when I click into the room). This happens predominately on the Slack theme, but I have also seen it on Dark and Normal.

**Comment by paveyry** [comment]
Is that with the firefox extension or with tampermonkey/greasemonkey?
I haven't been able to reproduce it so far

**Comment by rnc** [comment]
Its with the extension ; I'll try your new release and get back to you. I am using other (hopefully unrelated exensions) such as treestyle-tab, ublock,httpseverywhere .... I would presume that they shouldn't affect the interaction.

**Comment by rnc** [comment]
Ok so the default theme works perfectly (thanks!) but I am seeing issues with the Slack theme (haven't tested dark one). For example, when I am hovering over a channel with the mouse I see:
![image](https://user-images.githubusercontent.com/1169793/120294249-eadea780-c2bd-11eb-9849-e21444335b0e.png)

but when 'clicked' into that channel and focussed on a thread it shows as 

![image](https://user-images.githubusercontent.com/1169793/120294356-047fef00-c2be-11eb-8626-61ae0393b227.png)

i.e. there is no room highlight to show which room or direct message I am currently in. 

Should there be one in this mode?
