### ISSUE TITLE
Search Highlighting

### ISSUE THREAD

**Issue by BaReinhard** [paveyry/better-hangoutschat#4]
Search highlighting when using arrow keys doesn't show the hover effect.

command + k , then press down arrows.

The functionality exists but the styling isn't there.

**Comment by BaReinhard** [comment]
I've been playing around with the styling for this and still havent been able to find the right class to handle this.

**Comment by paveyry** [comment]
I can't either, I've been looking for this for a while but can't figure it out. If anybody knows which class to change, please let me know.
