### ISSUE TITLE
Installation instruction are not very clear

### ISSUE THREAD

**Issue by vipinagrahari** [paveyry/better-hangoutschat#5]

**Comment by BaReinhard** [comment]
I made a quick install script that might help

First make a backup of your asar file, I typically just run

```
cp /Applications/Chat.app/Contents/Resources/electron.asar ~/Desktop/electron.asar
```
Then create an install.sh in the root of this repo folder
```
#!/bin/bash

./generate_patch.sh $1 emojis_example.json 
cp out/theme/electron.asar /Applications/Chat.app/Contents/Resources/electron.asar
pkill Chat
sleep 1
open /Applications/Chat.app --args -AppCommandLineArg
```

Usage would be:
```
./install.sh ~/Desktop/electron.asar

**Comment by vipinagrahari** [comment]
Hey Thanks a lot. Got it running successfully. Adding this to readme will help others a lot

**Comment by chrisharrisonkiwi** [comment]
Any chance we can get an example of how to install the theme?
I'm not interested in emojis whatsoever...
I tried:
`./generate_patch.sh /Applications/Chat.app/Contents/Resources/electron.asar custom.css`

But got the error: `./generate_patch.sh: line 13: asar: command not found`

**Comment by chrisharrisonkiwi** [comment]
Figured it out.

`npm install -g asar` to install asar first...

**Comment by agribov** [comment]
Instructions are not clear for tampermonkey users either :-)

**Comment by paveyry** [comment]
It should be better now. I added details and it is now not necessary to install asar for the greasemonkey script
