### ISSUE TITLE
Navbar Alignment

### ISSUE THREAD

**Issue by MikeVensel** [paveyry/better-hangoutschat#7]
The feedback, Google apps menu and profile buttons on the left side of the navbar are misaligned. This doesn't happen if I make the window small enough but if I maximize it the issue occurs for me. I've attached a screenshot below. 

![image](https://user-images.githubusercontent.com/5809554/69251199-1340fe00-0b7f-11ea-88f2-08be75a5c7dc.png)

**Comment by paveyry** [comment]
Fixed here: https://github.com/paveyry/better-hangoutschat/commit/b67f3cf2ccfb8dcc6f3e82e7df2bb6c03ea4df1c
