### ISSUE TITLE
Provide the dark theme as UserCSS (for use with Stylus)

### ISSUE THREAD

**Issue by teohhanhui** [paveyry/better-hangoutschat#8]
See https://github.com/openstyles/stylus/wiki/Usercss

**Comment by teohhanhui** [comment]
It supports customization too (e.g. to pick an accent colour): https://github.com/openstyles/stylus/wiki/UserCSS-authors#var

**Comment by paveyry** [comment]
This is not something I am interested in spending time on. However, if you decide to do it yourself, you can submit a pull request and I'll be happy to include it in the repository.
